-- =============================================================================
-- Esquema Supabase: usa el script actual en:
--   scripts/supabase-schema-webapp-current.sql
--
-- Ese archivo define únicamente public.projects (modelo ItProject de la webapp),
-- elimina workflows, tablas puente workflow_* , plataformas y tecnologias, y
-- no modifica tablas de usuarios.
--
-- No ejecutes este archivo antiguo; puede chocar con el script nuevo.
-- =============================================================================
